### PR TITLE
clean up 05_mixedmodel, 07_phylo-t, and 08_results_summary

### PR DESCRIPTION
**Pull request by jwatzek**
**`07_phylo-t`** commit https://github.com/ManyPrimates/mp_pilot/pull/5/commits/f7b582b7b03dc43aeff31e95b5709b40bc67c895

**`08_results_summary`** commit https://github.com/ManyPrimates/mp_pilot/pull/5/commits/96d1c98fdc3082ad4534ead4416ef1239252bd3d

**`05_mixed_model`** commit https://github.com/ManyPrimates/mp_pilot/commit/d89a12e384a29045df2a6b9239e9765dfe338ddb

Two specific things to discuss from that (also left as notes in the `.nb.html` doc itself)
1. **Add pairwise contrasts for delay.** This wasn’t in the preregistration but, of course, yields the same conclusion as specifying another model with, say, ‘medium’ as the reference level or running another model that excludes ‘short’. And it’s a more elegant approach in my opinion.
1. **Remove another random effect.** For the reduced model, I would argue to also remove `trial` from the random slopes for subject/site as it’s near zero both in `mm.1` and even more so in `mm.2`. I’ve done so in the doc in `mm.3`

Thoughts?

### CODE REVIEW

**Comment by manuelbohn** [comment]
@1. Adding the pairwise comparisons makes sense. 

@2. Hm... I see your point. However, since it is not 0.000 (like the others were) I would leave it in there. Given that most subjects got 36 trials and trial was entered as a continuous predictor, the estimate itself is numerically small (0.04). Therefore, the variance (and std. dev) in the random effects is likely to be numerically small as well. Or does this not make sense?

**Comment by dmaltschul** [comment]
I'm having trouble with GitHub on my home computer after an update, so I'll need to do this on my work computer. Should be able to review tomorrow.

**Comment by dmaltschul** [comment]
@1. Pairwise contrasts might be interesting, and good from a sensitivity analysis standpoint.

@2. Its unfortunate that we don't have the CIs for the REs yet, but just glancing at the trial RE variances and sds, the sds are much larger than the variances, so the CIs would overlap with 0, and could justify removing them. However, as Manuel mentioned the trial REs aren't as degenerate as some others, so I had a look at the impact of removing the trial REs by comparing the nested models to empirically assess fit.
```
> anova(mm.3, mm.2)
Data: model.data
Models:  
mm.3: correct ~ condition * norm_age + task_experience + cup_distance + 
mm.3:     trial + (1 + condition | site/subject_site) + (1 + condition | 
mm.3:     species)
mm.2: correct ~ condition * norm_age + task_experience + cup_distance + 
mm.2:     trial + (1 + trial + condition | site/subject_site) + (1 + 
mm.2:     condition | species)
     Df    AIC    BIC  logLik deviance  Chisq Chi Df Pr(>Chisq)
mm.3 27 6840.2 7022.2 -3393.1   6786.2                         
mm.2 35 6851.5 7087.4 -3390.7   6781.5 4.7101      8     0.7881
```
So, the fit is better without those REs, which is certainly believable, though I cheated a bit by removing all the trial REs, instead of one by one. Anyway, we could certainly consider removing the weakest REs, but if we're going to do that, we need to be consistent, which would probably mean removing all REs that have CIs overlapping with 0 and testing to see if model fit improves.

This is also nice from a sensitivity standpoint, though it almost certainly will not at all change our results because a small RE won't have much impact on the model. I'm vaguely inclined to leave REs in place unless they are degenerate and/or causing a notable problem with model stability. What is our motivation for continuing to remove REs?

Also, new issue: why did species get added as a fixed effect to mm.2?

**Comment by jwatzek** [comment]
@dmaltschul thanks for looking this over!

Though hang on for a second, I think you may be looking at an old file. My proposed changes are on the `patch-1` branch. This pull request right here is for discussing those and potentially make more/fewer changes before merging it all into `master`. 

Let me know if you have trouble accessing that branch. Should just be `git checkout patch-1` after pulling the remote

**Comment by jwatzek** [comment]
@1 cool, I'll just remove that comment in the doc

@2 @manuelbohn "trial was entered as a continuous predictor, the estimate is numerically small (0.04). Therefore, the variance (and std. dev) in the random effects is likely to be small as well." Not necessarily. If you're thinking of the 0.04 as an (almost) flat line (not exactly, given that it's binomial), it's still possible for each subject (nested within site) to vary wildly from large negative slopes to large positive ones. That would still "on average" get you a 0.04 estimate on the fixed but a large var/sd on the random effect. Whereas in the model it's "everybody has essentially a zero slope on this"

@dmaltschul
The motivation is the same as for reducing the model/removing the other ones to begin with. Make a more parsimonious model that produces as good of a fit (or a better one even). As a minor/non-conceptual point, it also runs faster, which makes a difference for the CI calculation.

As for almost certainly not changing the result -- yes, 100% (and you can see that that's true in the `nb.html`). Exactly because it doesn't contribute that much. So in that sense, it certainly doesn't "really" matter whether we leave it in (and I'm happy to be outvoted on that) but you could say the same about removing the other ones. 

The main reason it caught my eye is that, just looking at the random effects plots of `mm.1` and `mm.2` (also in the doc), we've kicked out literally every other random effect that was just a straight vertical line (i.e., near-zero variability) except this one.

**Comment by jwatzek** [comment]
@dmaltschul by the way, the data has changed a tad. It's saved in `v2` and documentation for why and how is in PR #2

**Comment by dmaltschul** [comment]
Oh, yes, my repo hadn't sync'd to patch-1. Okay, having another look:

@2: That's certainly true about the RE for trial being so flat, and fits perfectly with the variance and sd values. There's certainly no real reason not to remove it, and particularly since the AIC tab and anova now convincingly demonstrate that we have a better fit model between 2 and 4.

Since this was a pilot, the pre-reg is maybe more vague than it should be, but there's allowances for analysis additions like this, and I think we have every reason to try to explore what model might be the best fit.

**Comment by manuelbohn** [comment]
Ok, you're right, we are learning a lot about pre-registration here. 

In the paper, we will probably report two models, one that is as close as possible to the pre-registered one and a second one which is the one that we think fits the data best. So let's remove the trial RE for the second one. 

@jwatzek feel free to merge in case this was the last open issue

**Pull request merged**
